# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.21.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.21.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rob/_CODE/C++/predator-prey-reinforcement-learning

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rob/_CODE/C++/predator-prey-reinforcement-learning

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.21.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rob/_CODE/C++/predator-prey-reinforcement-learning/CMakeFiles /Users/rob/_CODE/C++/predator-prey-reinforcement-learning//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rob/_CODE/C++/predator-prey-reinforcement-learning/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named predator-prey

# Build rule for target.
predator-prey: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 predator-prey
.PHONY : predator-prey

# fast build rule for target.
predator-prey/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/build
.PHONY : predator-prey/fast

src/agent.o: src/agent.cpp.o
.PHONY : src/agent.o

# target to build an object file
src/agent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/agent.cpp.o
.PHONY : src/agent.cpp.o

src/agent.i: src/agent.cpp.i
.PHONY : src/agent.i

# target to preprocess a source file
src/agent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/agent.cpp.i
.PHONY : src/agent.cpp.i

src/agent.s: src/agent.cpp.s
.PHONY : src/agent.s

# target to generate assembly for a file
src/agent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/agent.cpp.s
.PHONY : src/agent.cpp.s

src/direction.o: src/direction.cpp.o
.PHONY : src/direction.o

# target to build an object file
src/direction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/direction.cpp.o
.PHONY : src/direction.cpp.o

src/direction.i: src/direction.cpp.i
.PHONY : src/direction.i

# target to preprocess a source file
src/direction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/direction.cpp.i
.PHONY : src/direction.cpp.i

src/direction.s: src/direction.cpp.s
.PHONY : src/direction.s

# target to generate assembly for a file
src/direction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/direction.cpp.s
.PHONY : src/direction.cpp.s

src/env.o: src/env.cpp.o
.PHONY : src/env.o

# target to build an object file
src/env.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/env.cpp.o
.PHONY : src/env.cpp.o

src/env.i: src/env.cpp.i
.PHONY : src/env.i

# target to preprocess a source file
src/env.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/env.cpp.i
.PHONY : src/env.cpp.i

src/env.s: src/env.cpp.s
.PHONY : src/env.s

# target to generate assembly for a file
src/env.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/env.cpp.s
.PHONY : src/env.cpp.s

src/hunter.o: src/hunter.cpp.o
.PHONY : src/hunter.o

# target to build an object file
src/hunter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/hunter.cpp.o
.PHONY : src/hunter.cpp.o

src/hunter.i: src/hunter.cpp.i
.PHONY : src/hunter.i

# target to preprocess a source file
src/hunter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/hunter.cpp.i
.PHONY : src/hunter.cpp.i

src/hunter.s: src/hunter.cpp.s
.PHONY : src/hunter.s

# target to generate assembly for a file
src/hunter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/hunter.cpp.s
.PHONY : src/hunter.cpp.s

src/maddpg.o: src/maddpg.cpp.o
.PHONY : src/maddpg.o

# target to build an object file
src/maddpg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/maddpg.cpp.o
.PHONY : src/maddpg.cpp.o

src/maddpg.i: src/maddpg.cpp.i
.PHONY : src/maddpg.i

# target to preprocess a source file
src/maddpg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/maddpg.cpp.i
.PHONY : src/maddpg.cpp.i

src/maddpg.s: src/maddpg.cpp.s
.PHONY : src/maddpg.s

# target to generate assembly for a file
src/maddpg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/maddpg.cpp.s
.PHONY : src/maddpg.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/models.o: src/models.cpp.o
.PHONY : src/models.o

# target to build an object file
src/models.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/models.cpp.o
.PHONY : src/models.cpp.o

src/models.i: src/models.cpp.i
.PHONY : src/models.i

# target to preprocess a source file
src/models.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/models.cpp.i
.PHONY : src/models.cpp.i

src/models.s: src/models.cpp.s
.PHONY : src/models.s

# target to generate assembly for a file
src/models.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/models.cpp.s
.PHONY : src/models.cpp.s

src/prey.o: src/prey.cpp.o
.PHONY : src/prey.o

# target to build an object file
src/prey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/prey.cpp.o
.PHONY : src/prey.cpp.o

src/prey.i: src/prey.cpp.i
.PHONY : src/prey.i

# target to preprocess a source file
src/prey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/prey.cpp.i
.PHONY : src/prey.cpp.i

src/prey.s: src/prey.cpp.s
.PHONY : src/prey.s

# target to generate assembly for a file
src/prey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/prey.cpp.s
.PHONY : src/prey.cpp.s

src/replayBuffer.o: src/replayBuffer.cpp.o
.PHONY : src/replayBuffer.o

# target to build an object file
src/replayBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/replayBuffer.cpp.o
.PHONY : src/replayBuffer.cpp.o

src/replayBuffer.i: src/replayBuffer.cpp.i
.PHONY : src/replayBuffer.i

# target to preprocess a source file
src/replayBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/replayBuffer.cpp.i
.PHONY : src/replayBuffer.cpp.i

src/replayBuffer.s: src/replayBuffer.cpp.s
.PHONY : src/replayBuffer.s

# target to generate assembly for a file
src/replayBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/predator-prey.dir/build.make CMakeFiles/predator-prey.dir/src/replayBuffer.cpp.s
.PHONY : src/replayBuffer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... predator-prey"
	@echo "... src/agent.o"
	@echo "... src/agent.i"
	@echo "... src/agent.s"
	@echo "... src/direction.o"
	@echo "... src/direction.i"
	@echo "... src/direction.s"
	@echo "... src/env.o"
	@echo "... src/env.i"
	@echo "... src/env.s"
	@echo "... src/hunter.o"
	@echo "... src/hunter.i"
	@echo "... src/hunter.s"
	@echo "... src/maddpg.o"
	@echo "... src/maddpg.i"
	@echo "... src/maddpg.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/models.o"
	@echo "... src/models.i"
	@echo "... src/models.s"
	@echo "... src/prey.o"
	@echo "... src/prey.i"
	@echo "... src/prey.s"
	@echo "... src/replayBuffer.o"
	@echo "... src/replayBuffer.i"
	@echo "... src/replayBuffer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

